const TEAM_ALPHA2: Record<string, string> = {
  // CONMEBOL
  Argentina: 'ar',
  Brazil: 'br',
  Uruguay: 'uy',
  Colombia: 'co',
  Ecuador: 'ec',
  Paraguay: 'py',
  Chile: 'cl',
  Venezuela: 've',
  Peru: 'pe',
  Bolivia: 'bo',

  // CONCACAF
  'United States': 'us',
  USA: 'us',
  Mexico: 'mx',
  Canada: 'ca',
  Panama: 'pa',
  'Costa Rica': 'cr',
  Honduras: 'hn',
  Jamaica: 'jm',
  'El Salvador': 'sv',
  Guatemala: 'gt',
  Cuba: 'cu',
  Haiti: 'ht',
  'Trinidad and Tobago': 'tt',

  // UEFA
  France: 'fr',
  Spain: 'es',
  England: 'gb-eng',
  Germany: 'de',
  Portugal: 'pt',
  Netherlands: 'nl',
  Italy: 'it',
  Belgium: 'be',
  Switzerland: 'ch',
  Austria: 'at',
  Denmark: 'dk',
  Croatia: 'hr',
  Poland: 'pl',
  Serbia: 'rs',
  Czechia: 'cz',
  'Czech Republic': 'cz',
  Slovakia: 'sk',
  Slovenia: 'si',
  Ukraine: 'ua',
  Hungary: 'hu',
  Romania: 'ro',
  Turkey: 'tr',
  Türkiye: 'tr',
  Scotland: 'gb-sct',
  Wales: 'gb-wls',
  Greece: 'gr',
  Georgia: 'ge',
  Albania: 'al',
  Sweden: 'se',
  Norway: 'no',
  Finland: 'fi',
  Iceland: 'is',
  Ireland: 'ie',
  'Northern Ireland': 'gb-nir',
  Russia: 'ru',

  // CAF
  Morocco: 'ma',
  Senegal: 'sn',
  Egypt: 'eg',
  Nigeria: 'ng',
  Cameroon: 'cm',
  "Côte d'Ivoire": 'ci',
  'Ivory Coast': 'ci',
  Ghana: 'gh',
  'DR Congo': 'cd',
  'South Africa': 'za',
  Tunisia: 'tn',
  Algeria: 'dz',
  Mali: 'ml',
  Gabon: 'ga',
  Guinea: 'gn',
  Zambia: 'zm',
  Angola: 'ao',
  Kenya: 'ke',

  // AFC
  Japan: 'jp',
  'Korea Republic': 'kr',
  'South Korea': 'kr',
  Australia: 'au',
  Iran: 'ir',
  'Saudi Arabia': 'sa',
  Qatar: 'qa',
  Uzbekistan: 'uz',
  Iraq: 'iq',
  Indonesia: 'id',
  'United Arab Emirates': 'ae',
  China: 'cn',
  'China PR': 'cn',
  Syria: 'sy',
  Jordan: 'jo',
  Oman: 'om',
  Bahrain: 'bh',
  Kuwait: 'kw',
  India: 'in',
  Thailand: 'th',
  Vietnam: 'vn',

  // OFC
  'New Zealand': 'nz',
  Fiji: 'fj',
};

export function teamFlagUrl(teamName: string, width: 20 | 40 | 80 | 160 = 80): string | null {
  const code = TEAM_ALPHA2[teamName];
  if (!code) return null;
  return `https://flagcdn.com/w${width}/${code}.png`;
}
